config/routes.rb
Rails.application.routes.draw do
  root 'games#index'
  resources :frames
  resources :games
end

app/models/frame.rb
class Frame < ActiveRecord::Base
  belongs_to :game

  def pins_left
    if (self.idx === 10 && (self.is_strike || self.is_spare))
      10
    else
      10 - self.score
    end
  end

  def increase_score(pins)
    self.score += pins
    self.save
  end

  def set_strike_flag
    self.flag = 'strike'
    self.save
  end

  def set_spare_flag
    self.flag = 'spare'
    self.save
  end

  def is_spare
    self.flag === 'spare'
  end

  def is_strike
    self.flag === 'strike'
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :frames
  after_create :add_frames, :set_active

  def add_frames
    10.times { |i| self.frames << create_frame!(i+1) }
    self.save
  end

  def create_frame!(index)
    Frame.create(
      roll1_pins: 0, 
      roll2_pins: 0,
      roll3_pins: 0,
      idx: index
    )
  end
  
  def set_active
    self.current_frame = 1
    self.current_roll = 1
    self.save
  end

  def get_frame(index)
    self.frames[index - 1]
  end

  def update_score!(pins)
    #work with current frame
    cur_frame = get_frame(self.current_frame)
    
    #if strike
    if pins === 'X'
      cur_frame.set_strike_flag
      pins = 10
    end

    #if spare    
    if pins === '/'
      cur_frame.set_spare_flag
      pins = cur_frame.pins_left
      pins = 10 - cur_frame.roll1_pins if self.current_frame === 10
    end
    pins = pins.to_i

    #check pins number
    raise 'Incorrect Pins Number!' if ( pins > 10 || pins < 0 )
    
    #set pins for separate rolls
    case self.current_roll
    when 1
      cur_frame.roll1_pins = pins
    when 2
      cur_frame.flag = 'spare' if (pins == cur_frame.pins_left)
      cur_frame.roll2_pins = pins
    when 3
      cur_frame.roll3_pins = pins
    end
    cur_frame.increase_score(pins)

    #Additional points if it strike or spare.
    cur1frame = get_frame(self.current_frame - 1)
    cur2frame = get_frame(self.current_frame - 2)
    if cur1frame.is_strike && cur2frame.is_strike && 
      (self.current_roll == 1 || (self.current_roll == 2 && self.current_frame != 10))
      cur1frame.increase_score(pins)
      cur2frame.increase_score(pins)
    elsif cur1frame.is_strike && (self.current_roll == 1 || self.current_roll == 2)
      cur1frame.increase_score(pins)
    elsif cur1frame.is_spare && self.current_roll == 1
      cur1frame.increase_score(pins)
    end
          
    #check if game is finished
    if (self.current_frame == 10)
      if (!cur_frame.is_strike && !cur_frame.is_spare && self.current_roll === 2) || 
         ((cur_frame.is_strike || cur_frame.is_spare) && self.current_roll === 3)
        self.is_finished = true;
      end
    end

    #increment frame
    if (self.current_roll === 2 && self.current_frame != 10)
      self.current_frame += 1
    end

    #increment roll
    if (self.current_roll === 2 && self.current_frame == 10 && (cur_frame.is_strike || cur_frame.is_spare))
      self.current_roll = 3  
    else
      self.current_roll = (self.current_roll === 1) ? 2 : 1
    end
    
    #if is strike
    if (cur_frame.is_strike && self.current_frame != 10)
      self.current_frame += 1
      self.current_roll = 1
    end

    #update total score
    sum = 0
    self.frames.each { |frame| sum += frame.score }
    self.score = sum
    
    #save the game
    self.save
  end

  def pins_left
    get_frame(self.current_frame).pins_left
  end

  def is_last_strike
    self.current_frame == 10 && get_frame(10).is_strike
  end

  def is_last_spare
    self.current_frame == 10 && get_frame(10).is_spare
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  def index
    @games = Game.all
  end

  # GET /games/1
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was stared. Have fun.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /games/1
  def update
    respond_to do |format|
      if @game.update_score!(params[:pins])
        format.html { redirect_to @game, notice: 'Score was updated. Go Ahead!' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /games/1
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
      p @game
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frames_helper.rb
module FramesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/frames/_form.html.erb
<%= form_for(@frame) do |f| %>
  <% if @frame.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@frame.errors.count, "error") %> prohibited this frame from being saved:</h2>

      <ul>
      <% @frame.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :is_active %><br>
    <%= f.check_box :is_active %>
  </div>
  <div class="field">
    <%= f.label :roll1_pins %><br>
    <%= f.number_field :roll1_pins %>
  </div>
  <div class="field">
    <%= f.label :roll2_pins %><br>
    <%= f.number_field :roll2_pins %>
  </div>
  <div class="field">
    <%= f.label :roll3_pins %><br>
    <%= f.number_field :roll3_pins %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/frames/edit.html.erb
<h1>Editing frame</h1>

<%= render 'form' %>

<%= link_to 'Show', @frame %> |
<%= link_to 'Back', frames_path %>

app/views/frames/index.html.erb
<h1>Listing frames</h1>

<table>
  <thead>
    <tr>
      <th>Is active</th>
      <th>Roll1 pins</th>
      <th>Roll2 pins</th>
      <th>Roll3 pins</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @frames.each do |frame| %>
      <tr>
        <td><%= frame.is_active %></td>
        <td><%= frame.roll1_pins %></td>
        <td><%= frame.roll2_pins %></td>
        <td><%= frame.roll3_pins %></td>
        <td><%= link_to 'Show', frame %></td>
        <td><%= link_to 'Edit', edit_frame_path(frame) %></td>
        <td><%= link_to 'Destroy', frame, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Frame', new_frame_path %>

app/views/frames/new.html.erb
<h1>New frame</h1>

<%= render 'form' %>

<%= link_to 'Back', frames_path %>

app/views/frames/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Is active:</strong>
  <%= @frame.is_active %>
</p>

<p>
  <strong>Roll1 pins:</strong>
  <%= @frame.roll1_pins %>
</p>

<p>
  <strong>Roll2 pins:</strong>
  <%= @frame.roll2_pins %>
</p>

<p>
  <strong>Roll3 pins:</strong>
  <%= @frame.roll3_pins %>
</p>

<%= link_to 'Edit', edit_frame_path(@frame) %> |
<%= link_to 'Back', frames_path %>

app/views/games/_form.html.erb
<%= form_for(@game, :html=>{:class => 'cfx new_game'}) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>
      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Playing Game</h1>

<%= render 'form' %>

<!--%= link_to 'Show', @game %> | -->
<%= link_to 'Back to Games', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>
<p id="notice"><%= notice %></p>
<table class="game-list">
  <thead>
    <tr>
      <th>Name</th>
      <th>Score</th>
      <th>Is finished</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.score %></td>
        <td><%= game.is_finished ? 'yes' : 'no' %></td>
          <td><%= link_to('Continue Playing', game) if !game.is_finished %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Play New Game &rarr;'.html_safe, new_game_path %>

app/views/games/new.html.erb
<h1>Start New Game</h1>
<%= render 'form' %>
<%= link_to '&larr; Back to Games'.html_safe, games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Player Name:</strong>
  <%= @game.name %>
</p>

    <%= form_tag @game, :method => :put, :class => "score-calculator"  do %>
      <table class="calc-score-table">
        <thead>
          <tr>
            <td colspan=2>Frame 1</td>
            <td colspan=2>Frame 2</td>
            <td colspan=2>Frame 3</td>
            <td colspan=2>Frame 4</td>
            <td colspan=2>Frame 5</td>
            <td colspan=2>Frame 6</td>
            <td colspan=2>Frame 7</td>
            <td colspan=2>Frame 8</td>
            <td colspan=2>Frame 9</td>
            <td colspan=3>Frame 10</td>
            <td>Score</td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <% @game.frames.each_with_index do |frame, index| %>
              <td class="score">
                <%= frame.roll1_pins == 10 ? 'X' : frame.roll1_pins  %>
              </td>
              <td class="score">
                <%= (frame.roll1_pins + frame.roll2_pins == 10 && frame.roll2_pins > 0) ? '/' : frame.roll2_pins == 10 ? 'X' : frame.roll2_pins %>
              </td>
              <% if 9 === index %>
                <td class="add score"><%= frame.roll3_pins == 10 ? 'X' : frame.roll3_pins %></td>
              <% end %>
            <% end %>
            <td class="game-result" rowspan="2"><%= @game.score %></td>
          </tr>
          <tr>
            <% @game.frames.each_with_index do |frame, index| %>
              <td colspan="<%= (9 === index)? 3 : 2 %>" class="frame"><%= frame.score %></td>
            <% end %>
          </tr>
        </tbody>
      </table>

      <% unless @game.is_finished %>
      <div class="calc-buttons-container cfx">
        <div class="row cfx">
          <% 10.times do |i| %>
            <% if (i <= @game.pins_left) %>
              <input name="pins" type="submit" value="<%= i %>">
            <% end %>
          <% end %>
          <% if @game.current_roll > 1 && @game.pins_left && @game.current_frame != 10 %>
            <input name="pins" type="submit" value="/">
          <% end %>
          <% if @game.current_frame === 10 || @game.current_roll === 1 %>
            <input name="pins" type="submit" value="X">
          <% end %>
        </div>
        <div class="row cfx">
          <%= link_to 'Play New Game', new_game_path %>
        </div>
      </div>
      <% else %>
        <p>Game is finished. Your <strong>score is </strong><%= @game.score %>. See you again!</p>
      <% end %>
    <% end %>

<%= link_to '&larr; Back to Games'.html_safe, games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TenPin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class ='wrapper'>
<%= link_to '&larr; To Game List'.html_safe, root_path %>

<%= yield %>

</div>
</body>
</html>